;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        isearch-forward-regexp
        isearch-other-control-char
        isearch-printing-char
        sp--self-insert-command
        tags-loop-continue
        ))
